### PR TITLE
Fixed : code quality issues

### PR DESCRIPTION
**Pull request by ankitdobhal**
## Description

Hi 👋 I ran the [DeepSource](https://deepsource.io/) static analyzer on the forked copy of this repo and found some [interesting code quality issues](https://deepsource.io/gh/ankitdobhal/supysonic/issues/). This PR fixes a few of them.

## Summary of Fixes

- Remove unnecessary return statement 
- Remove unnecessary `del` statement from local scope
- Consider merging the comparisons with 'in'
- Added .deepsource.toml to fix bug risks

## Type of change

- [✔] Antipattern
- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [✔] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by ankitdobhal** [comment]
@spl0k kindly review the PR.

**Comment by spl0k** [comment]
Hello.
Interesting stuff this DeepSource thing.

The PR looks good. Could you just format it using `black` please?

**Comment by ankitdobhal** [comment]
> Hello.
> Interesting stuff this DeepSource thing.
> 
> The PR looks good. Could you just format it using `black` please?

@spl0k thanks for response .
[DeepSource](https://deepsource.io/) can automatically run **black**, **isort** **autopep8** in the **PRs**, that are automated.
you can enable it after the current PR is merged and  activated DeepSource.

Activating analysis will help you to continuously analyze repo for code quality issues and fix commonly occurring issues using the auto-fix feature. 

To activate [DeepSource](https://deepsource.io/) you just need to follow these small steps:

- Install DeepSource on your repository [here](https://deepsource.io/signup).
- create .deepsource.toml configuration which you can use to configure your analysis settings.
> Note: This PR already have .deepsource.toml file you just need to merge this PR.
- Activate analysis [here](https://deepsource.io/gh/pashmaklang/pashmak).

**Comment by spl0k** [comment]
I've merged your fixes.
As for the DeepSource integration, I'll evaluate the solution before enabling it on the repository, making my own unbiased opinion.

**Comment by ankitdobhal** [comment]
> I've merged your fixes.
> As for the DeepSource integration, I'll evaluate the solution before enabling it on the repository, making my own unbiased opinion.

You can merge the PR rather then closing  it , I will recommend kindly to merge this it was not necessary for you to add deepsource just depends on you. But I thing you can merge the PR rather then closing .

**Comment by ankitdobhal** [comment]
> I've merged your fixes.
> As for the DeepSource integration, I'll evaluate the solution before enabling it on the repository, making my own unbiased opinion.

Hi @spl0k have you evaluated the solutions ?

**Pull request closed without merging**
