### PR TITLE
remove directory with weird mojibake encoding

### PR DESCRIPTION
**Pull request by baldurmen**
I don't know how that directory was created (and it's been there for a year already...) but suddently my Debian QA tools freaked out on this weirdly encoded thing...

```
oo@bar:~/git/supysonic/tests/assets$ ls -l
total 148
drwxr-xr-x 2 emiliano emiliano  4096 avr  1 22:51 ''$'\346'
-rw-r--r-- 1 emiliano emiliano    23 avr  1 22:51  23bytes
-rw-r--r-- 1 emiliano emiliano    33 avr  1 22:51  23bytes.txt
-rw-r--r-- 1 emiliano emiliano  6155 avr  1 22:51  cover.jpg
-rw-r--r-- 1 emiliano emiliano     0 avr  1 22:51  empty
drwxr-xr-x 2 emiliano emiliano  4096 avr  1 22:51  folder
drwxr-xr-x 2 emiliano emiliano  4096 avr  1 22:51  formats
-rw-r--r-- 1 emiliano emiliano  1955 avr  1 22:51  issue133.flac
-rw-r--r-- 1 emiliano emiliano  2760 avr  1 22:51  issue139.aac
-rw-r--r-- 1 emiliano emiliano 85812 avr  1 22:51  issue139.mp3
-rw-r--r-- 1 emiliano emiliano   229 avr  1 22:51  sample.ini
-rw-r--r-- 1 emiliano emiliano 24235 avr  1 22:51  subsonic-rest-api-1.9.0.xsd
```

Bash also showed the char as `�/`

### CODE REVIEW

**Comment by baldurmen** [comment]
FWIW, the commit that created that is 270fa9883b2f2bc98f1482a68f7d9022017af50b

**Comment by spl0k** [comment]
This folder is here to test that the scanner doesn't bork with badly encoded paths (even if there is no specific test for this kind of issues).
You got the wrong commit, see #85 and 954c75bc358916ebb53fdc689225f855ec773cde

Maybe a better approach would have been to create this folder during a test rather than versioning it 🤔

**Comment by spl0k** [comment]
It seems no test tries to scan this folder anymore, and that the error on badly encoded path reappeared 😮 
This will be merged and (re)fixed in a few minutes.

**Comment by baldurmen** [comment]
Ah, thanks for the follow up. Makes sense. Turns out one of our QA tool broke and this helped find a bug :)

I do think generating that directory during the tests and cleaning it afterwards makes much more sense though, as a bunch of things don't like badly encoded paths.

**Comment by pR0Ps** [comment]
Thanks for merging this - it was causing me headaches when trying to develop on MacOS (Linux was fine)

**Pull request merged**
