### PR TITLE
WIP: Unit tests

### PR DESCRIPTION
**Pull request by ogarcia**
I'm writing some unit tests.

I send this PR to have a place to anotate the small bugs that I could found writing the tests. I think that is better that are open an issue for every minimal bug.

The tests can be launched with the following command.
```
python -m unittest -v tests
```

When the PR will be ready to merge, I'll let you know.

### CODE REVIEW

**Comment by ogarcia** [comment]
Writing the test for add folder I see that [this line][1] seems that never execute. I think that lines [63][2] and [64][1] can be removed and return `FolderManager.SUBPATH_EXISTS` when `any(path.startswith(p) for p in store.find(Folder).values(Folder.path))`.

If you make this change, then we should modify `test_add_folder` to expect `FolderManager.SUBPATH_EXISTS` on subfolder test.

[1]: https://github.com/ogarcia/supysonic/blob/master/supysonic/managers/folder.py#L64
[2]: https://github.com/ogarcia/supysonic/blob/master/supysonic/managers/folder.py#L63

**Comment by ogarcia** [comment]
In [frontend login check][1] must be an other check that test if userid correspond with username. I can pass a valid userid with an invalid username. I think some like:
```python
elif UserManager.get(store, session.get('userid'))[1].name != session.get('username'):
    session.clear()
    should_login = True
```

[1]: https://github.com/spl0k/supysonic/blob/master/supysonic/frontend/__init__.py#L29

**Comment by spl0k** [comment]
About your last comment, the `username` session value is actually some quick an dirty way to display the user name on every page and is used just for that purpose. I don't really think a check would be needed here.
And [setting this session cookie](https://github.com/spl0k/supysonic/blob/5fb98d96f5ea2c69d9cf09fcaa2288a5477ad262/supysonic/frontend/user.py#L235) could even be removed if you changed the way it's handled with #65.

**Comment by ogarcia** [comment]
Hi @spl0k 

I'll close this PR because it has be merged in #69

**Pull request closed without merging**
