### PR TITLE
[Do Not Merge] Handle scanning operations in a background process

### PR DESCRIPTION
**Pull request by TaizoSimpson**
Addresses issue #77, part 2 (don't "block" when scanning from web UI)

This PR moves any scanning that occurs when using the web UI (really only {frontend}/folder/scan) to another process that is started alongside the Flask app.  As a result, when scanning the database from the web ui, the HTTP request can be returned instantly while the scanning occurs in the background, a opposed to the current system, where the request isn't returned until the scanning operation is complete, which could take a very long time.

I admit, my solution is a little more complicated than some of the other solutions to this problem, but I think that this will end up working better in the long run.  By having one and only one process in charge of scanning, progress can easily be queried and tracked from anywhere with the ability to communicate with the master process.  The alternative approach of creating a new process or thread whenever a request to scan is made could result in having multiple scanning threads at once, and might make it difficult to track and query progress from any one of them.  Additionally, this will hopefully make it easier to implement the official API for scanning (addressed later).  It also doesn't make it impossible to have multithreaded scanning as per part 1 of issue 77, because this implementation doesn't touch the Scanner.scan method, which can still be multi threaded without issue.

Currently, to connect to the scanner process, you create a `ScannerClient` object with some information about how to connect to the master process.  In order to make this information available from any process that Flask might create, it is pickled and base64 encoded before being put in the `scanner_location` field of the Meta table in the database.  Ultimately, the whole connection process looks like:

    sc =  ScannerClient(
        pickle.loads(
            base64.b64decode(
                Meta['scanner_location'].value
    )))

From this point, the ScannerClient class provides a fairly simple api for use.

Under the hood, it's a little bit more complicated, because the process needs to be able to handle connections to multiple other threads simultaneously.  After a process is spawned using `create_process()`, two different threads are set up.  The first is the scanner thread, which wait for folder ids to appear in it's queue before scanning them one at a time.  The second is the parent thread, which opens a `multiprocessing.Listener` and awaits new connections from new `ScannerClient`s.  When it receives one, it creates a new thread dedicated to serving the requests of the new client until the connection is closed.

Commands sent to the scanning thread come in the form of a tuple, where the first entry is a string representing the command, for example `SCAN` or `SHUTDOWN`, and all remaining entries are arguments to that command.  The `ScannerClient` just sends these commands and awaits a response, if relevant.

Hopefully, this should make implementing the official scanning API much easier, although I've held off on implementing it in this PR because it seemed like a can of worms not worth opening until this is confirmed or denied.

### CODE REVIEW

**Comment by spl0k** [comment]
Hi.
Some notes on this PR:

The `Meta.value` field is limited to 256 characters. I don't know if Pony checks the length before sending `INSERT` or `UPDATE` commands or if it only relies on the DB backend enforcing it but if that's the latter case you might not get any errors if you're using SQLite because it "ignores" any field limit.
So be sure that this pickling+base64 doesn't exceed 256 characters or it will break with MySQL and Postgres.

I'm a bit worried about the scanner process starting when a Flask application handles its first request. Depending on how the web API is served (Apache's mod_wsgi, gunicorn, uwsgi, etc.) you might have multiple Flask applications running at the same time, thus probably spinning up several scanning processes. Furthermore in the mod_wsgi case the application isn't kept running alongside with Apache's processes but is torn down a few second after the last request has been answered.
Also since we now have an additional process we're exposing ourselves to new errors and it seems to me some aren't handled. Let's suppose we kill this new process while the Flask application is still running. If there's an existing `ScannerClient` by that time I suppose calling some of its methods will result in an exception being thrown. Same goes for instantiating a new `ScannerClient` such as in the `/folder/scan` endpoint.

One idea to handle scanning in another process would be to repurpose the watcher a bit (`supysonic-watcher` or `watcher.py`) to make it able to receive commands from other processes and scan the whole library rather than only individual files. That would require the watcher to be running in order to request a scan from the web UI but if you don't want to start the watcher you could still scan from the CLI. That would also pave the way for #77 part 5, if the watcher is able to receive command we can now tell it to schedule new `Observer`s.
Going this way would also benefit the CLI as one could use it to request a background scan rather than blocking the terminal while it is scanning.

The multithreaded scan (#77 part 1) was just some idea I threw without any testing. Before going for it one should do some profiling in order to determine if it is really needed. I see three points where the scanning time could be used:
- database lookups. Adding indexes would help reduce the time spent querying the database.
- disk I/O. Unless the media library is spread across multiple disks I doubt any parallelizing would help compress that time.
- if none of the above is time consuming and the majority of the time is spent in the Python code only then a threading could help improve the scanning performance. And that's only assuming the gain isn't limited by the GIL otherwise we would have to go, once again, look towards multiprocessing.

**Comment by TaizoSimpson** [comment]
Honestly, I think this PR should probably just be scrapped.  I did a lot of re-inventing the wheel, which is the source of a number of your concerns.  Between multiprocessing's pools and managers, almost the entire ScannerMaster class I wrote here can be abstracted and left to Python, and running multiple scanning processes at once practically implements itself.  That said, some of the problems still remain, like how to communicate the status of the manager process, and how to start it.

I don't think the length of the address/authkey pickle should ever be a problem on most sane systems.  With the address `/tmp/pymp-9x20griy/listener-mvl2yqly` and eight random bytes, the b64 encoded pickle is 78 characters long.  Once the program has an address, it could pretty easily test it by trying to connect.

As for starting the scanner, I personally feel like putting the scanning process in with the watcher might make more unnecessary work for users who weren't previously using the watcher, but want to benefit from background scanning.  I had thought that `@before_first_request` somehow worked with wsgi servers to coordinate and only run once, but I just tested it and sure enough, you were right.  However, I think it might still be possible to do as part of the main process, perhaps by starting it after detecting that the address currently in the database is "dead".

You're also right about multithreaded scanning being sub-optimal.  There's [a branch on my repo right now][1] where I tried to implement it and found that it was slightly slower than a single thread implementation.

Trial|Single Threaded|Multithreaded
-|-|-
1|2.145|2.815
2|2.193|2.805
3|2.215|2.817

> Scanning my personal library on an SSD, 639 tracks, roughly 21G.  All measurements in seconds

And attempting to read the results of the profiler, it does look like most time is spent in database lookups (as long as I'm reading it right, which, considering I haven't touched it until now, I might not be).  However, I think I'm going to keep working on my multiprocessing implementation (not the multithreading one linked above), because even if the parallelism doesn't help, it's so much more elegant than this PR for handling scanning in a background process.

[1]: https://github.com/TaizoSimpson/supysonic/tree/multithread-scanner

**Comment by TaizoSimpson** [comment]
Closing, replaced by #127

**Comment by spl0k** [comment]
How did you come to the conclusion that the time is spent in the database? I ran some "quick" tests and found a different suspect. See my last comment on #77.

**Comment by TaizoSimpson** [comment]
I was using the cProfile module.  I don't still have my results, unfortunately, but it reported a vast majority of the time being spent on one of ponyorm's methods.  I'd be fairly willing to assume that I'm using the tool wrong though, since I've never really used it before.

**Pull request closed without merging**
