### PR TITLE
Initial ListenBrainz support

### PR DESCRIPTION
**Pull request by ivan-avalos**
I'm finally making this happen! https://github.com/spl0k/supysonic/issues/80#issuecomment-1405881111

# TODO
- [x] Feedback from @spl0k.
- [x] Update documentation.
- [x] Modify config examples.
- [x] Write tests and test the tests.
- [ ] Approval from @spl0k.

### CODE REVIEW

**Comment by ivan-avalos** [comment]
Any word about this merge request?

**Comment by spl0k** [comment]
Sorry, I didn't had the time to look at it yet, I'm quite busy at the moment. I'll try to do it this weekend.

**Comment by ivan-avalos** [comment]
It's okay, thanks for the update. Please feel free to check it out whenever you have time. Just wanted to make sure it didn't fly under your radar.

**Comment by spl0k** [comment]
Hello. It's nice to see a pull request that has everything covered, not only the implementation but also migrations, tests and documentation 👍 

I spotted a bug though: one can't link or unlink their token if they're not an admin. This is most likely due to the fact that you only use the full user id in the template and not the special `me` id. Note that it could also be seen as a bug in the `me_or_uuid` decorator.

**Comment by ivan-avalos** [comment]
> I spotted a bug though: one can't link or unlink their token if they're not an admin. This is most likely due to the fact that you only use the full user id in the template and not the special `me` id. Note that it could also be seen as a bug in the `me_or_uuid` decorator.

Sorted! Please check my last commit.

**Comment by spl0k** [comment]
👍 merged.

**Pull request merged**
