### PR TITLE
Minor updates to documentation and config organization/defaults

### PR DESCRIPTION
**Pull request by ddd999**
Just some minor changes to things that tripped me up during initial installation.

Config.sh is probably not the most elegant solution,  but it's a start.

### CODE REVIEW

**Comment by andrenam** [comment]
Hm, I dont think there should be any code thats specific for a certain distribution. Thats the job of a package maintainer, if theres any.
What was wrong with a single configuration file?

**Comment by ddd999** [comment]
Fair point. I think a default config file would be a useful addition though.

**Comment by andrenam** [comment]
Yup, +1

**Comment by spl0k** [comment]
Added configuration sample with 0c86085fe2a4b2d8a928146cbdf2e5cadccc2df7 and 62642cc07916e713a54720c7bb6fb5c55d25fcb2.

**Pull request closed without merging**
